### ISSUE TITLE
bug in Apple Midi notify callback setup in sound_apple_midi.hpp

### ISSUE THREAD

**Issue by designerfuzzi** [maks/pixilang#2]
seems there are mutliple bugs, as the nature of coding smuggles them in.. but this one is obvious.
bug in Apple Midi notify callback setup in **sound_apple_midi.hpp**

https://github.com/maks/pixilang/blob/58c54aaa1e8695f4791053b3476a08fe49bbf467/lib_sundog/sound/sound_apple_midi.hpp#L313

the notify function `midi_notify_callback`  should not be passed as `&` reference but simply with its address.
means the `&` is not needed..

in some cases bridging is needed .. 
like bridging in:  `notifyRefCon = (__bridge void*)sd->ss` 
and bridging out: `sunvox_engine *sd = (__bridge sunvox_engine*)refCon;` in midi_notifiy_callback..
otherwise sd will be released in the callback and crash at the very next access here `uint32_t w = sd->midi_notify_cmds_w;`

**Comment by maks** [comment]
Thank you for filing this issue, but this repo is just a mirror of the Pixilang sourcecode distribution from https://warmplace.ru/soft/pixilang/ so you would be best to raise any issues with NightRadio, the author and maintainer of Pixilag on his forum: https://warmplace.ru/forum/viewforum.php?f=6&sid=010f0f756e6946a6dc1177c37fed42e6
